/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

/**
 * Structurally identical to kysely's ColumnType, defined locally so this
 * package has no dependencies and lambdas stay fully self contained.
 */
type ColumnType<SelectType, InsertType = SelectType, UpdateType = SelectType> = {
  readonly __select__: SelectType;
  readonly __insert__: InsertType;
  readonly __update__: UpdateType;
};

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BranchDonors {
  contact_email: string | null;
  contact_name: string | null;
  created_at: Generated<Timestamp | null>;
  donor_id: Generated<number>;
  organization: string;
}

export interface BranchExpenditures {
  admin_notes: string | null;
  amount: Numeric;
  category: string | null;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  entered_by: number | null;
  expenditure_id: Generated<number>;
  project_id: number;
  receipt_url: string | null;
  spent_on: Generated<Timestamp>;
  status: Generated<string>;
}

export interface BranchProjectDonations {
  amount: Numeric;
  donated_at: Generated<Timestamp | null>;
  donation_id: Generated<number>;
  donor_id: number;
  project_id: number;
}

export interface BranchProjectMemberships {
  hours: Numeric | null;
  membership_id: Generated<number>;
  project_id: number;
  role: string;
  start_date: Timestamp | null;
  user_id: number;
}

export interface BranchProjects {
  created_at: Generated<Timestamp | null>;
  currency: Generated<string | null>;
  description: string;
  end_date: Timestamp | null;
  name: string;
  project_id: Generated<number>;
  start_date: Timestamp | null;
  total_budget: Numeric | null;
}

export interface BranchReports {
  date_created: Generated<Timestamp>;
  object_url: string;
  project_id: number;
  report_id: Generated<number>;
  report_type: Generated<string>;
  title: string;
}

export interface BranchUsers {
  cognito_sub: string | null;
  created_at: Generated<Timestamp | null>;
  email: string;
  is_admin: Generated<boolean | null>;
  name: string;
  profile_image: string | null;
  user_id: Generated<number>;
}

export interface DB {
  "branch.donors": BranchDonors;
  "branch.expenditures": BranchExpenditures;
  "branch.project_donations": BranchProjectDonations;
  "branch.project_memberships": BranchProjectMemberships;
  "branch.projects": BranchProjects;
  "branch.reports": BranchReports;
  "branch.users": BranchUsers;
}
