openapi: 3.0.3
info:
  title: users (Local)
  version: 1.0.0
servers:
  - url: /
paths:
  /users/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean

  /users:
    get:
      summary: GET /users
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: OK
    post:
      summary: POST /users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                isAdmin:
                  type: boolean
                profileImage:
                  type: string
      responses:
        '201':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /users/{userId}:
    get:
      summary: GET /users/{userId}
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: User not found
    patch:
      summary: PATCH /{userId}
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                isAdmin:
                  type: boolean
                profileImage:
                  type: string
      responses:
        '200':
          description: OK
        '404':
          description: User not found
    delete:
      summary: DELETE /users/{userId}
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
